import { Component } from '@angular/core';
import { NavController } from 'ionic-angular';
import { InfoPage } from '../info/info';
import { FavoritoPage } from '../favorito/favorito';


@Component({
  selector: 'page-home',
  templateUrl: 'home.html'
})
export class HomePage {
  info = InfoPage;
  favorito = FavoritoPage;
  Fav = [];
  casas = [
    {vendedor: "Capital Brokers", descripcion: "Casa en Pre-Venta en Puerta de Hierro, Excelente Residencia con terminados de lujo y de primera calidad, cuenta con 4 recámaras, más una de visitas en planta baja la cual tiene entrada independiente, la cochera es para 8 autos, 3 cuartos de servicio, 13 baños completos, área de lavado y aire acondicionado en las habitaciones; El material de los pisos al interior de la casa es mármol sirio, en la cocina es cuarzo y el tipo de madera es rosa morada, acabados de yeso en todos los muros. Cuenta también con gimnasio y spa, 3 bodegas, cocina para el personal de servicio, Family Room, Bar, Jacuzzi, Preparación para Sistema Inteligente, Elevador, Espacio para Mascotas y 2 cisternas de 20 mil litros.", ubicacion: "Puerta de Hierro", precio: "$60,000,000", terreno: "1,618 m2 ", imagen: "../assets/Casa1.jpg", telefono: "(33) 1649 3934"},
    {vendedor: "JPK Experiencia Inmobiliaria", descripcion: "Hermosa Residencia en Coto Aragón, desarrollo Puerta de Hierro, enclavada en la zona de mayor plusvalía de la zona Metropolitana de Guadalajara, anexo se encuentra el mejor centro Comercial, cerca de Colegios, Universidades y más. Su diseño clásico con detalles de lujo", ubicacion: "Puerta de Hierro, coto Aragón", precio: "$26,000,000", terreno: "908 m2", imagen: "../assets/Casa2.jpg", telefono: "(33) 3620 3200"},
    {vendedor: "Capital Brokers", descripcion: "Planta alta: recamara principal con vestidor amplio, baño con tina, terraza. 2 recamaras secundarias cada una con vestidor y baño. Planta baja: recamara con baño completo, bar, sala, comedor, cocina, terraza, jardín, patio de servicio. cuarto de servicio/juegos independientes de la casa, cochera para 4 autos 20 años de antigüedad, en buen estado de conservación. Casa club con alberca", ubicacion: "San Bernardo, Puerta de Hierro", precio: "$12,000,000", terreno: "500 m2", imagen: "../assets/Casa3.jpg", telefono: "(33) 1649 3934"},
    {vendedor: "Iliana Torres Gari y Asociados", descripcion: "Casa de lujo nueva 3 niveles en sótano cochera para 4 autos cuarto de máquinas área de lavado cuarto de servicio con baño sala de entretenimiento con baño y terraza preparaciones para elevador que conecta todas las planta en planta baja recibidor estudio baño completo cocina comedor estar terraza y área de jardín en planta alta, estar de tv 1 recamara principal con 2 closet/vestidor, baño con jacuzzi y balcón 2 recamaras c/u con baño completo vestidor y terraza compartida 1 recamara con baño closet.", ubicacion: "Reserva Real", precio: "$22,500,000", terreno: "508 m2", imagen: "../assets/Casa4.jpg", telefono: "(33) 8526 1526"},
    {vendedor: "Iliana Torres Gari y Asociados", descripcion: "Casa de lujo nueva 3 niveles en sótano cochera para 4 autos área de lavado cuarto de servicio con baño sala de entretenimiento con baño completo y terraza privada. En planta baja recibidor estudio baño completo cocina comedor estar terraza y área de jardín con asador. En planta alta estar de tv 1 recamara principal con closet/vestidor, baño con jacuzzi, 2 recamaras c/u con baño completo vestidor, 1 recamara con baño completo y closet, vertedero y salida hacia azotea oculta, y closet de blancos.", ubicacion: "Jardin Real", precio: "$11,000,000", terreno: "303 m2", imagen: "../assets/Casa5.jpg", telefono: "(33) 8526 1526"},
    {vendedor: "Sierra Providencia", descripcion: "Casa en venta en Hacienda Mirage, totalmente nueva, acabados de lujo en toda la casa, 3 recámaras, principal se encuentra en planta baja con baño completo y vestidor, cocina integral con barra de granito negro, sala y comedor a doble altura ampli jardín alrededor de toda la casa, terraza, aire acondicionado en toda la casa, a solo 5 minutos de López Mateos Sur.", ubicacion: "Hacienda Mirage, Tlajomulco de Zuñiga", precio: "8,500,000", terreno: "522 m2", imagen: "../assets/Casa6.jpg", telefono: "(33) 3055 0222"},
    {vendedor: "Socios Mundo Inmobiliario", descripcion: "Magnífica residencia de lujo dentro del exclusivo condominio La Ceiba, en la zona de Juan Palomar y Periférico. Cuenta con seguridad y acceso controlado las 24 horas, circuito cerrado en todas las áreas comunes, cerca electrificada en todo el perímetro, únicamente 60 casas, cuenta con vigilancia, alberca, cancha de tenis y terraza para eventos sociales, se pagan $2,016 pesos trimestrales de mantenimiento. La casa es ideal para inversión y ampliar, cuenta cochera para 2 autos, cocina integral de granito, sala comedor, jardin, en ese mismo nivel cuenta con 2 recámaras, la principal con vestidor y baño, la segunda con baño completo para compartir el área social, en planta alta tiene una recamara con baño completo y clóset, 2 terrazas y área de lavado. ", ubicacion: "Valle Real", precio: "$7,900,000", terreno: "306 m2", imagen: "../assets/Casa7.jpg", telefono: "(33) 8526 1746"},
    {vendedor: "Capital Brokers", descripcion: "El proyecto de estilo arquitectónico contemporáneo, cuenta con una extensión de terreno de 1500 m2 y un área de construcción de 1013 m2. Al interior, la casa se diseñó en 2 niveles con la idea de privilegiar el uso de la Planta Baja con las 2 recámaras o suites principales así como áreas sociales y de entretenimiento. Al subir a la Planta Alta por elevador o por escaleras, encontramos otra recámara con baño completo y vestidor, además de una terraza descubierta y acceso a áreas de servicio. En Planta Baja, encontramos un vestíbulo de ingreso con fuente, medio baño de visitas, 2 dos estudios o despachos distribuidos en ambos extremos del patio central, que cuenta con domo retráctil automático, para tener la opción de disfrutar el buen clima o bien cubrirse de la lluvia. Dicho patio central decorado con árboles de interior y un muro verde genera un cálido espacio que integra y divide a la vez las áreas sociales de las recámaras. La sala y el comedor con pisos de maderas finas, son amplios espacios muy iluminados con ventanales que conectan la terraza y el jardín. La cocina es integral con moderno diseño italiano, tiene una barra de granito rojo, equipada con lavavajillas, horno convencional, horno de microondas, amplia alacena con gabinetes de diseño de la marca American Closets. Las suites principales tienen amplios baños y vestidores cada una, así como una sala familiar intermedia con vista y acceso a los jardines. El área de servicio cuenta con cuarto con baño completo y closet para personal, lavandería, patio para tendederos y escalera de servicio. En el ingreso además se cuenta con caseta de acceso, cuarto y baño completo para vigilante y bodega. La casa está rodeada con barda perimetral, caseta de control de ingreso, equipo de cámaras de vigilancia y cochera con portón eléctrico para 6 autos.", ubicacion: "Colinas de San Javier", precio: "$45,000,000", terreno: "1,500 m2", imagen: "../assets/Casa8.jpg", telefono: "(33) 2005 1560"},
    {vendedor: "Sierra Providencia", descripcion: "Casa en venta en Villa Verona, super lujo, mármol en toda la casa, 3 recámaras con baño completo y vestidor, estudio con opción a 4ta recámara, 2 terrazas, una en planta baja con cantina y jardín, otra en planta alta, cuenta con acceso y preparación para roof garden, estacionamiento para 3 autos, el fraccionamiento cuenta cn casa club con alberca y áreas verdes.", ubicacion: "Villa Verona, Valle Real", precio: "$13,490,000", terreno: "333 m2", imagen: "../assets/Casa9.jpg", telefono: "(33) 3055 0222"},
    {vendedor: "Capriori Bienes Raices", descripcion: "Casa en Cañadas, de 3 recamaras cada uno con baño completo, estacionamiento para 4 autos, estudio con baño completo, alberca, sala de T/V, cuarto de servicio, sala doble altura, salón de juegos, family room y calentador solar", ubicacion: "Las Cañadas", precio: "$11,800,000", terreno: "630 m2", imagen: "../assets/Casa10.jpg", telefono: "(33) 1729 8304"}
  ]

  constructor(public navCtrl: NavController) {

  }
  clickDatos(c)
  {
    this.navCtrl.push(this.info,{casa:c, favorito:this.Fav});
  }
  clickAgregar()
  {
    this.navCtrl.push(this.favorito, {favorito: this.Fav});
  }
}
